### ISSUE TITLE
Why is there this statement in the script? file was deleted!

### ISSUE THREAD

**Issue by hnboy2005** [matthewyang204/NotepadEE#2] opened 2024-07-16 03:03 UTC
<img width="566" alt="image" src="https://github.com/user-attachments/assets/8ce2b2e3-da37-4279-852c-4cc876f41877">

**Comment by matthewyang204** [comment] 2024-07-18 14:58
Yeah, the installer has weird stuff in it, when it tries to copy new files, it runs into errors. Don't use the installer, just download the AMD64 linux binary from 3.0.0 or compile the 3.1.0 yourself, and then put the folder into /opt/matthewyang. It'll create the ~/Library by itself. Also, the problem is, this app was designed to run on Macs to begin with, so there are things that aren't in Linux.

**Comment by matthewyang204** [comment] 2024-07-18 14:59
I have also removed the Mac CLI installer, as it has other stuff that causes conflicts when downloading.

**Comment by matthewyang204** [comment] 2024-07-18 15:01
Also, that installer downloads the 3.0.0 build, not 3.1.0, which is the latest Linux can run as of now.

**Comment by matthewyang204** [comment] 2024-07-19 00:40
I'll close this thread with an explanation of why the installer does that:
The Library folder on Macs contains the Caches folder, which holds certain variables and other things that were stored in RAM that are written to disk. So Notepad=='s textarea and file paths are all things stored in the RAM that need to be written to disk in order to autosave. However, it needs to store these things separate from the file you are editing so that it doesn't overwrite. However, it is a Linux system, not a Mac system. So, it has to create the Caches folder inside of a Library folder.

However, the installer says it can't create a new folder because it already exists. As it's just a disk cache, it refreshes the caches, clearing them, therefore deleting the Library directory. The app, however, checks if a folder already exists there, and automatically creates it if it doesn't exist. The installer is just buggy and runs into weird issues. Don't use it, just download the precompiled release 3.0.0 or compile 3.1.0 yourself, and then you can just copy it to /opt/matthewyang/Notepad==. And then add the .desktop file from the 3.0.0 file to /usr/share/applications/. That's the way I prefer people to do it. I've had many bad previous experiences with the CLI installers.

**Closed by matthewyang204** 2024-07-19 00:40 UTC
